[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "modulekit/=lib/modulekit/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "BokkyPooBahsDateTimeLibrary/=lib/BokkyPooBahsDateTimeLibrary/",
    "safe-singleton-deployer/=lib/safe-singleton-deployer-sol/src/",
    # ModuleKit dependencies
    "erc4337-validation/=lib/modulekit/node_modules/@rhinestone/erc4337-validation/src/",
    "@ERC4337/=lib/modulekit/node_modules/@ERC4337/",
    "account-abstraction/=lib/modulekit/node_modules/@ERC4337/account-abstraction/contracts/",
    "account-abstraction-v0.6/=lib/modulekit/node_modules/@ERC4337/account-abstraction-v0.6/contracts/",
    "@rhinestone/=lib/modulekit/node_modules/@rhinestone/",
    "ds-test/=lib/modulekit/node_modules/ds-test/src/",
    "solady/=lib/modulekit/node_modules/solady/src/",
    "solarray/=lib/modulekit/node_modules/solarray/src/",
    "@prb/math/=lib/modulekit/node_modules/@prb/math/src/",
    "ExcessivelySafeCall/=lib/modulekit/node_modules/excessively-safe-call/src/"
]
solc = "0.8.30"
optimizer = true
optimizer_runs = 200

[lint]
exclude_lints = ["asm-keccak256"]
